### ISSUE TITLE
Unable to view init container logs in deployments page

### ISSUE THREAD

**Issue by thorweijie** [aptakube/aptakube#456]
### Current and expected behavior

Current behaviour: When I was investigating the native sidecar resource issue (#452), I noticed that in pods page (second image), I can see the logs of the nginx main container, as well as the 2 init containers (istio-validation and istio-proxy). However in deployments page (third image), I can only see the logs of the nginx main container.

Expected behaviour: I expect to see 3 containers (1 pod x (1 main container + 2 init containers)) in deployments page.

<img width="854" alt="Image" src="https://github.com/user-attachments/assets/acc01400-e0d9-4039-9c73-9350a4c2b98d" />
<img width="1553" alt="Image" src="https://github.com/user-attachments/assets/a10b4e9f-3283-4d10-9293-ed6acd7b94e9" />
<img width="1538" alt="Image" src="https://github.com/user-attachments/assets/31ac9354-756e-491b-9ad0-6b70872513b4" />

### Environment & Operating System

macOS Sequoia 15.5

**Comment by goenning** [comment]
Hey @thorweijie I've been working on a new version of the log viewer (with a bunch of other features/improvements), and this bug should be fixed on it. Would you like to give it a try?

https://releases.aptakube.com/Aptakube_1.12.0-beta4_universal.dmg

**Comment by thorweijie** [comment]
@goenning I am still unable to view init container logs in deployments view. On an unrelated note, is it possible to add sidecar containers to the pods view so it's easier to exec into the container? In the first image, I would like to see istio-proxy present, in addition to nginx and nginx2.

<img width="857" height="879" alt="Image" src="https://github.com/user-attachments/assets/eedefea6-9175-4974-bbe8-0e0095f0dd06" />
<img width="1554" height="198" alt="Image" src="https://github.com/user-attachments/assets/aaff9bc4-40a7-4d57-8604-ee121383b89d" />

**Comment by goenning** [comment]
On your second image, there's nothing below the "Init Containers" label? The image seems cropped 

On your first image, the sidecar is there, below ngnix2. And there are buttons to exec into it. Did I miss something?

**Comment by thorweijie** [comment]
I've added a full screenshot, there's nothing below the init containers label
<img width="1556" height="983" alt="Image" src="https://github.com/user-attachments/assets/3fda17f6-803b-4db8-bc71-1d0044f86a31" />

I was wondering if it's possible to add a tab for istio-proxy at the top? So it's easier to jump to the container
<img width="1249" height="444" alt="Image" src="https://github.com/user-attachments/assets/cca4b687-4e78-416a-a270-eb57f7c64c2c" />

**Comment by goenning** [comment]
Would you mind sharing your nginx deployment YAML (remove anything sensitive). This is how it should look:

<img width="1274" height="474" alt="Image" src="https://github.com/user-attachments/assets/235ba7fa-fc84-406a-8799-dc00c9a27605" />

As for the tab, I think that makes sense 👍

**Comment by thorweijie** [comment]
Here is the deployment yaml, the init containers were injected by Istio's mutating webhook
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    sidecar.istio.io/inject: "true"
  name: nginx
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - image: nginx
          imagePullPolicy: Always
          name: nginx2
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```

**Comment by goenning** [comment]
I'd like to see the `initContainers` section, can you get that from the YAML tab after the injection?

**Comment by thorweijie** [comment]
I couldn't see the `initContainers` section from the deployment spec
```
kubectl get deploy nginx -oyaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2025-01-27T03:36:50Z"
  generation: 4
  labels:
    app: nginx
    sidecar.istio.io/inject: "true"
  name: nginx
  namespace: default
  resourceVersion: "4620028964"
  uid: eeaec0d4-b2fc-4065-bb8a-c8fd29ece173
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - image: nginx
        imagePullPolicy: Always
        name: nginx2
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2025-01-27T03:36:50Z"
    lastUpdateTime: "2025-07-10T02:58:11Z"
    message: ReplicaSet "nginx-7f557dbd45" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-07-10T12:57:46Z"
    lastUpdateTime: "2025-07-10T12:57:46Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 4
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```
But I can see the `initContainers` section from the pod spec. If you have access to a Kubernetes cluster, you can reproduce this by following the steps to download Istio [here](https://istio.io/latest/docs/setup/getting-started/#download), and run the following commands to install Istio with the native sidecar feature flag enabled together with nginx:
```
istioctl install --set values.pilot.env.ENABLE_NATIVE_SIDECARS=true
kubectl label namespace default istio-injection=enabled
kubectl create deploy nginx --image=nginx
```

```
kubectl get po nginx-7f557dbd45-psjq5 -oyaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 21ab6771e36dda694c9d7105cbd2b6037a9083bdbab2fa2618eb72d04d8a498d
    cni.projectcalico.org/podIP: 100.96.1.168/32
    cni.projectcalico.org/podIPs: 100.96.1.168/32
    istio.io/rev: default
    kubectl.kubernetes.io/default-container: nginx
    kubectl.kubernetes.io/default-logs-container: nginx
    prometheus.io/path: /stats/prometheus
    prometheus.io/port: "15020"
    prometheus.io/scrape: "true"
    sidecar.istio.io/interceptionMode: REDIRECT
    sidecar.istio.io/status: '{"initContainers":["istio-validation","istio-proxy"],"containers":null,"volumes":["workload-socket","credential-socket","workload-certs","istio-envoy","istio-data","istio-podinfo","istio-token","istiod-ca-cert"],"imagePullSecrets":["xxx"],"revision":"default"}'
    traffic.sidecar.istio.io/excludeInboundPorts: "15020"
    traffic.sidecar.istio.io/includeInboundPorts: '*'
    traffic.sidecar.istio.io/includeOutboundIPRanges: '*'
  creationTimestamp: "2025-07-10T02:57:59Z"
  generateName: nginx-7f557dbd45-
  labels:
    app: nginx
    networking.istio.io/tunnel: http
    pod-template-hash: 7f557dbd45
    security.istio.io/tlsMode: istio
    service.istio.io/canonical-name: nginx
    service.istio.io/canonical-revision: latest
    sidecar.istio.io/inject: "true"
  name: nginx-7f557dbd45-psjq5
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-7f557dbd45
    uid: 15eb8be1-956c-4a0d-948f-ef9453fd81cc
  resourceVersion: "4620064753"
  uid: 72a702e7-f3ff-4df3-9f58-433de1d91d5e
spec:
  containers:
  - env:
    - name: KUBERNETES_SERVICE_HOST
      value: xxx
    image: nginx
    imagePullPolicy: Always
    name: nginx
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
  - env:
    - name: KUBERNETES_SERVICE_HOST
      value: xxx
    image: nginx
    imagePullPolicy: Always
    name: nginx2
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: xxx
  initContainers:
  - args:
    - istio-iptables
    - -p
    - "15001"
    - -z
    - "15006"
    - -u
    - "1337"
    - -m
    - REDIRECT
    - -i
    - '*'
    - -x
    - ""
    - -b
    - '*'
    - -d
    - 15090,15021,15020
    - --log_output_level=default:info
    - --run-validation
    - --skip-rule-apply
    env:
    - name: ISTIO_META_ENABLE_HBONE
      value: "true"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.ip=$(INSTANCE_IP)
    image: xxx
    imagePullPolicy: Always
    name: istio-validation
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
  - args:
    - proxy
    - sidecar
    - --domain
    - $(POD_NAMESPACE).svc.cluster.local
    - --proxyLogLevel=warning
    - --proxyComponentLogLevel=misc:error
    - --log_output_level=default:info
    env:
    - name: PILOT_CERT_PROVIDER
      value: istiod
    - name: CA_ADDR
      value: istiod.istio-system.svc:15012
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    - name: INSTANCE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
    - name: SERVICE_ACCOUNT
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.serviceAccountName
    - name: HOST_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    - name: ISTIO_CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.cpu
    - name: PROXY_CONFIG
      value: |
        {"tracing":{"zipkin":{"address":"jaeger.istio-system.svc.cluster.local:9411"},"sampling":10},"envoyAccessLogService":{"address":"gateway-proxy-access-logger.istio-system:8083","tlsSettings":{}},"proxyMetadata":{"ISTIO_META_ENABLE_HBONE":"true","OTEL_RESOURCE_ATTRIBUTES":"k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.ip=$(INSTANCE_IP)"},"holdApplicationUntilProxyStarts":false}
    - name: ISTIO_META_POD_PORTS
      value: |-
        [
        ]
    - name: ISTIO_META_APP_CONTAINERS
      value: nginx,nginx2
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.memory
    - name: GOMAXPROCS
      valueFrom:
        resourceFieldRef:
          divisor: "0"
          resource: limits.cpu
    - name: ISTIO_META_CLUSTER_ID
      value: Kubernetes
    - name: ISTIO_META_NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: ISTIO_META_INTERCEPTION_MODE
      value: REDIRECT
    - name: ISTIO_META_WORKLOAD_NAME
      value: nginx
    - name: ISTIO_META_OWNER
      value: kubernetes://apis/apps/v1/namespaces/default/deployments/nginx
    - name: ISTIO_META_MESH_ID
      value: cluster.local
    - name: TRUST_DOMAIN
      value: cluster.local
    - name: ISTIO_META_ENABLE_HBONE
      value: "true"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: k8s.pod.name=$(POD_NAME),k8s.namespace.name=$(POD_NAMESPACE),k8s.pod.ip=$(INSTANCE_IP)
    image: xxx
    imagePullPolicy: Always
    lifecycle:
      preStop:
        exec:
          command:
          - pilot-agent
          - request
          - --debug-port=15020
          - POST
          - drain
    name: istio-proxy
    ports:
    - containerPort: 15090
      name: http-envoy-prom
      protocol: TCP
    readinessProbe:
      failureThreshold: 4
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 3
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 128Mi
    restartPolicy: Always
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 1337
      runAsNonRoot: true
      runAsUser: 1337
    startupProbe:
      failureThreshold: 1200
      httpGet:
        path: /healthz/ready
        port: 15021
        scheme: HTTP
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 3
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
  nodeName: xxx
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: bin-packing-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: workload-socket
  - emptyDir: {}
    name: credential-socket
  - emptyDir: {}
    name: workload-certs
  - emptyDir:
      medium: Memory
    name: istio-envoy
  - emptyDir: {}
    name: istio-data
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.labels
        path: labels
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: istio-podinfo
  - name: istio-token
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          audience: istio-ca
          expirationSeconds: 43200
          path: istio-token
  - configMap:
      defaultMode: 420
      name: istio-ca-root-cert
    name: istiod-ca-cert
  - name: kube-api-access-mj5jz
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T02:58:01Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T02:58:04Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T13:03:04Z"
    message: 'containers with unready status: [nginx2]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T13:03:04Z"
    message: 'containers with unready status: [nginx2]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-07-10T02:57:59Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://fc0a2222d55d01019b2d81b586ac71e09a8d24ff5851b81198825ca5124f23b5
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:93230cd54060f497430c7a120e2347894846a81b6a5dd2110f7362c5423b4abc
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-07-10T02:58:09Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://5288f4ee305186907f8e0951e201af7ba35f29e58cab7389c1a76625efe6f073
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:93230cd54060f497430c7a120e2347894846a81b6a5dd2110f7362c5423b4abc
    lastState:
      terminated:
        containerID: containerd://5288f4ee305186907f8e0951e201af7ba35f29e58cab7389c1a76625efe6f073
        exitCode: 1
        finishedAt: "2025-07-10T13:03:04Z"
        reason: Error
        startedAt: "2025-07-10T13:02:59Z"
    name: nginx2
    ready: false
    restartCount: 121
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=nginx2 pod=nginx-7f557dbd45-psjq5_default(72a702e7-f3ff-4df3-9f58-433de1d91d5e)
        reason: CrashLoopBackOff
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.250.7.216
  hostIPs:
  - ip: 10.250.7.216
  initContainerStatuses:
  - containerID: containerd://47e019160a98de28d398296181124d40b9b32f7fbc9fde59970c5f1dd77a7c4b
    image: xxx
    imageID: xxx
    lastState: {}
    name: istio-validation
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://47e019160a98de28d398296181124d40b9b32f7fbc9fde59970c5f1dd77a7c4b
        exitCode: 0
        finishedAt: "2025-07-10T02:58:01Z"
        reason: Completed
        startedAt: "2025-07-10T02:58:01Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
      recursiveReadOnly: Disabled
  - containerID: containerd://87144f76855da586668d7e0ba97e0cd31b78bf06a2d495b7852983c16bc5d22d
    image: xxx
    imageID: xxx
    lastState: {}
    name: istio-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-07-10T02:58:01Z"
    volumeMounts:
    - mountPath: /var/run/secrets/workload-spiffe-uds
      name: workload-socket
    - mountPath: /var/run/secrets/credential-uds
      name: credential-socket
    - mountPath: /var/run/secrets/workload-spiffe-credentials
      name: workload-certs
    - mountPath: /var/run/secrets/istio
      name: istiod-ca-cert
    - mountPath: /var/lib/istio/data
      name: istio-data
    - mountPath: /etc/istio/proxy
      name: istio-envoy
    - mountPath: /var/run/secrets/tokens
      name: istio-token
    - mountPath: /etc/istio/pod
      name: istio-podinfo
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mj5jz
      readOnly: true
      recursiveReadOnly: Disabled
  phase: Running
  podIP: 100.96.1.168
  podIPs:
  - ip: 100.96.1.168
  qosClass: Burstable
  startTime: "2025-07-10T02:57:59Z"
```

**Comment by goenning** [comment]
Oh, so that must be why. It seems like Istio injects the InitContainers into the pods when they're created, and not on the deployment. So from the deployment point of view, there's no initContainers 🤔 

I need to think how i'll solve this...

**Comment by goenning** [comment]
@thorweijie OK I think I this one should work now (it also includes a lot of other fixes / improvements)

https://releases.aptakube.com/Aptakube_1.12.0-beta5_universal.dmg

**Comment by thorweijie** [comment]
@goenning I can confirm init container logs are working now, thanks for fixing!

**Comment by goenning** [comment]
Released on 1.12.0
